name: CI - Run ESLint

on:
  workflow_run:
    workflows: [ "CI - Run NPM audit" ]
    types: [ completed ]
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
